// lib/constants.ts

const BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? ''

export const STATS = [
  { value: '32,364', label: 'Fire Hotspots', color: '#e63946' },
  { value: '1.0%', label: 'Inside Protected Areas', color: '#2d6a4f' },
  { value: 'September', label: 'Peak Fire Month', color: '#e76f51' },
  { value: '329', label: 'Hotspots in Protected Zones', color: '#457b9d' },
]

export const PERU_VIEW = {
  longitude: -75.0,
  latitude: -9.5,
  zoom: 5,
}

export const MAP_STYLE = 'https://tiles.openfreemap.org/styles/positron'

export const LAYERS = [
  {
    id: 'hotspots' as const,
    label: '🔴 Fire Hotspots',
    color: '#e63946',
    dataUrl: `${BASE}/data/fire_hotspots.geojson`,
  },
  {
    id: 'protected' as const,
    label: '🟩 Protected Areas',
    color: '#2d6a4f',
    dataUrl: `${BASE}/data/protected_areas.geojson`,
  },
  {
    id: 'indigenous' as const,
    label: '🟣 Indigenous Territories',
    color: '#8338ec',
    dataUrl: `${BASE}/data/indigenous_territories.geojson`,
  },
  {
    id: 'boundary' as const,
    label: '⬜ Country Boundary',
    color: '#457b9d',
    dataUrl: `${BASE}/data/country_boundary.geojson`,
  },
] as const

export type LayerId = (typeof LAYERS)[number]['id']

export const SKILL_TAGS = [
  '🗺️ GIS · QGIS · ArcGIS Pro',
  '🛰️ MODIS · FIRMS · Sentinel-2',
  '🐍 Python · Pandas · DBSCAN',
  '📊 Spatial Analysis · Visualization',
]

export const YEAR_RANGE = { min: 2000, max: 2024 }

export const LAND_GOV_STATS = [
  { type: 'Unprotected Forest',      count: 31925, pct: 98.6, color: '#6c757d' },
  { type: 'National Protected Area', count: 329,   pct: 1.0,  color: '#2d6a4f' },
  { type: 'Regional Conservation',   count: 105,   pct: 0.3,  color: '#457b9d' },
  { type: 'Private Conservation',    count: 5,     pct: 0.0,  color: '#f4a261' },
] as const

export const ANNUAL_STATS: { year: number; hotspots: number; burnedArea: number }[] = [
  { year: 2001, hotspots: 28,   burnedArea: 320  },
  { year: 2002, hotspots: 660,  burnedArea: 942  },
  { year: 2003, hotspots: 1264, burnedArea: 2881 },
  { year: 2004, hotspots: 915,  burnedArea: 1452 },
  { year: 2005, hotspots: 2137, burnedArea: 6759 },
  { year: 2006, hotspots: 1053, burnedArea: 1991 },
  { year: 2007, hotspots: 1950, burnedArea: 3061 },
  { year: 2008, hotspots: 1351, burnedArea: 1561 },
  { year: 2009, hotspots: 1033, burnedArea: 1541 },
  { year: 2010, hotspots: 1741, burnedArea: 5129 },
  { year: 2011, hotspots: 1058, burnedArea: 1096 },
  { year: 2012, hotspots: 1940, burnedArea: 3064 },
  { year: 2013, hotspots: 1164, burnedArea: 1908 },
  { year: 2014, hotspots: 853,  burnedArea: 1715 },
  { year: 2015, hotspots: 1450, burnedArea: 2032 },
  { year: 2016, hotspots: 1479, burnedArea: 4037 },
  { year: 2017, hotspots: 928,  burnedArea: 1532 },
  { year: 2018, hotspots: 1299, burnedArea: 1945 },
  { year: 2019, hotspots: 1721, burnedArea: 3010 },
  { year: 2020, hotspots: 1533, burnedArea: 3972 },
  { year: 2021, hotspots: 1313, burnedArea: 1694 },
  { year: 2022, hotspots: 1718, burnedArea: 4975 },
  { year: 2023, hotspots: 1502, burnedArea: 2439 },
  { year: 2024, hotspots: 2227, burnedArea: 6198 },
]

export const REGIONAL_STATS: Record<string, { region: string; count: number }[]> = {
  'all': [
    { region: 'Puerto Inca', count: 4390 },
    { region: 'Padre Abad', count: 3857 },
    { region: 'Coronel Portillo', count: 3461 },
    { region: 'Tambopata', count: 2399 },
    { region: 'Bellavista', count: 1988 },
    { region: 'Tahuamanu', count: 1986 },
    { region: 'Mariscal Cáceres', count: 1562 },
    { region: 'Oxapampa', count: 1250 },
    { region: 'Satipo', count: 1016 },
    { region: 'Ucayali', count: 842 },
    { region: 'Alto Amazonas', count: 842 },
    { region: 'La Convención', count: 763 },
    { region: 'Lamas', count: 657 },
    { region: 'Picota', count: 650 },
    { region: 'San Martín', count: 609 },
    { region: 'Huallaga', count: 607 },
    { region: 'Leoncio Prado', count: 569 },
    { region: 'Atalaya', count: 509 },
    { region: 'Tocache', count: 431 },
    { region: 'Marañón', count: 403 },
  ],
  '2000': [
    { region: 'Jaén', count: 14 },
    { region: 'Utcubamba', count: 10 },
    { region: 'Luya', count: 9 },
    { region: 'San Ignacio', count: 6 },
    { region: 'Datem del Marañón', count: 2 },
    { region: 'Cajamarca', count: 1 },
    { region: 'Mariscal Cáceres', count: 1 },
    { region: 'Chota', count: 1 },
    { region: 'Rioja', count: 1 },
    { region: 'Rodríguez de Mendoza', count: 1 },
    { region: 'Moyobamba', count: 1 },
  ],
  '2001': [
    { region: 'Chanchamayo', count: 8 },
    { region: 'Tahuamanu', count: 6 },
    { region: 'Padre Abad', count: 3 },
    { region: 'La Convención', count: 2 },
    { region: 'Coronel Portillo', count: 2 },
    { region: 'Paucartambo', count: 1 },
    { region: 'La Mar', count: 1 },
    { region: 'Tarma', count: 1 },
    { region: 'Puerto Inca', count: 1 },
    { region: 'Lamas', count: 1 },
    { region: 'Jaén', count: 1 },
    { region: 'San Ignacio', count: 1 },
  ],
  '2002': [
    { region: 'Puerto Inca', count: 101 },
    { region: 'Tambopata', count: 94 },
    { region: 'Padre Abad', count: 84 },
    { region: 'Mariscal Cáceres', count: 41 },
    { region: 'Coronel Portillo', count: 38 },
    { region: 'Tahuamanu', count: 32 },
    { region: 'Bellavista', count: 32 },
    { region: 'Oxapampa', count: 30 },
    { region: 'La Convención', count: 25 },
    { region: 'Huallaga', count: 23 },
    { region: 'Lamas', count: 17 },
    { region: 'Satipo', count: 15 },
    { region: 'Chanchamayo', count: 14 },
    { region: 'Leoncio Prado', count: 12 },
    { region: 'Ucayali', count: 12 },
    { region: 'Picota', count: 12 },
    { region: 'El Dorado', count: 11 },
    { region: 'Maynas', count: 7 },
    { region: 'San Martín', count: 6 },
    { region: 'Alto Amazonas', count: 6 },
  ],
  '2003': [
    { region: 'Puerto Inca', count: 190 },
    { region: 'Padre Abad', count: 137 },
    { region: 'Coronel Portillo', count: 109 },
    { region: 'Tambopata', count: 82 },
    { region: 'Bellavista', count: 82 },
    { region: 'Mariscal Cáceres', count: 79 },
    { region: 'Oxapampa', count: 72 },
    { region: 'Tahuamanu', count: 57 },
    { region: 'Picota', count: 57 },
    { region: 'Huallaga', count: 44 },
    { region: 'La Convención', count: 36 },
    { region: 'Satipo', count: 36 },
    { region: 'Leoncio Prado', count: 29 },
    { region: 'Lamas', count: 27 },
    { region: 'Ucayali', count: 23 },
    { region: 'El Dorado', count: 23 },
    { region: 'Tocache', count: 20 },
    { region: 'Chanchamayo', count: 18 },
    { region: 'San Martín', count: 17 },
    { region: 'Alto Amazonas', count: 15 },
  ],
  '2004': [
    { region: 'Tambopata', count: 91 },
    { region: 'Puerto Inca', count: 80 },
    { region: 'Bellavista', count: 73 },
    { region: 'Padre Abad', count: 72 },
    { region: 'Mariscal Cáceres', count: 67 },
    { region: 'Huallaga', count: 45 },
    { region: 'Picota', count: 43 },
    { region: 'Alto Amazonas', count: 43 },
    { region: 'Coronel Portillo', count: 41 },
    { region: 'Satipo', count: 39 },
    { region: 'Lamas', count: 39 },
    { region: 'Tahuamanu', count: 38 },
    { region: 'Oxapampa', count: 29 },
    { region: 'Marañón', count: 27 },
    { region: 'El Dorado', count: 25 },
    { region: 'San Martín', count: 19 },
    { region: 'Tocache', count: 14 },
    { region: 'La Convención', count: 13 },
    { region: 'Ucayali', count: 12 },
    { region: 'Leoncio Prado', count: 9 },
  ],
  '2005': [
    { region: 'Puerto Inca', count: 255 },
    { region: 'Tambopata', count: 212 },
    { region: 'Padre Abad', count: 201 },
    { region: 'Coronel Portillo', count: 183 },
    { region: 'Bellavista', count: 116 },
    { region: 'Tahuamanu', count: 109 },
    { region: 'La Convención', count: 102 },
    { region: 'Mariscal Cáceres', count: 85 },
    { region: 'Satipo', count: 82 },
    { region: 'Oxapampa', count: 79 },
    { region: 'Leoncio Prado', count: 61 },
    { region: 'Alto Amazonas', count: 50 },
    { region: 'Huallaga', count: 44 },
    { region: 'Lamas', count: 41 },
    { region: 'Ucayali', count: 40 },
    { region: 'Picota', count: 40 },
    { region: 'Chanchamayo', count: 36 },
    { region: 'Tocache', count: 35 },
    { region: 'Marañón', count: 32 },
    { region: 'San Martín', count: 28 },
  ],
  '2006': [
    { region: 'Puerto Inca', count: 134 },
    { region: 'Padre Abad', count: 126 },
    { region: 'Bellavista', count: 86 },
    { region: 'Tambopata', count: 74 },
    { region: 'Coronel Portillo', count: 69 },
    { region: 'Mariscal Cáceres', count: 55 },
    { region: 'San Martín', count: 42 },
    { region: 'Alto Amazonas', count: 42 },
    { region: 'Lamas', count: 41 },
    { region: 'Leoncio Prado', count: 29 },
    { region: 'Picota', count: 29 },
    { region: 'Oxapampa', count: 28 },
    { region: 'Huallaga', count: 26 },
    { region: 'Satipo', count: 25 },
    { region: 'Tahuamanu', count: 25 },
    { region: 'La Convención', count: 24 },
    { region: 'Jaén', count: 20 },
    { region: 'Chanchamayo', count: 19 },
    { region: 'Tocache', count: 17 },
    { region: 'Ucayali', count: 14 },
  ],
  '2007': [
    { region: 'Puerto Inca', count: 247 },
    { region: 'Padre Abad', count: 202 },
    { region: 'Coronel Portillo', count: 192 },
    { region: 'Bellavista', count: 167 },
    { region: 'Tambopata', count: 121 },
    { region: 'Mariscal Cáceres', count: 111 },
    { region: 'Picota', count: 92 },
    { region: 'Alto Amazonas', count: 85 },
    { region: 'Tahuamanu', count: 76 },
    { region: 'Oxapampa', count: 72 },
    { region: 'Lamas', count: 71 },
    { region: 'La Convención', count: 56 },
    { region: 'Leoncio Prado', count: 54 },
    { region: 'Huallaga', count: 43 },
    { region: 'El Dorado', count: 41 },
    { region: 'San Martín', count: 37 },
    { region: 'Satipo', count: 35 },
    { region: 'Ucayali', count: 34 },
    { region: 'Chanchamayo', count: 18 },
    { region: 'Moyobamba', count: 18 },
  ],
  '2008': [
    { region: 'Puerto Inca', count: 216 },
    { region: 'Padre Abad', count: 146 },
    { region: 'Mariscal Cáceres', count: 111 },
    { region: 'Bellavista', count: 105 },
    { region: 'Tambopata', count: 91 },
    { region: 'Coronel Portillo', count: 84 },
    { region: 'Oxapampa', count: 60 },
    { region: 'Tahuamanu', count: 51 },
    { region: 'Ucayali', count: 46 },
    { region: 'Satipo', count: 42 },
    { region: 'La Convención', count: 38 },
    { region: 'Huallaga', count: 38 },
    { region: 'Alto Amazonas', count: 38 },
    { region: 'Picota', count: 34 },
    { region: 'San Martín', count: 32 },
    { region: 'Lamas', count: 32 },
    { region: 'El Dorado', count: 26 },
    { region: 'Chanchamayo', count: 19 },
    { region: 'Maynas', count: 16 },
    { region: 'Atalaya', count: 13 },
  ],
  '2009': [
    { region: 'Puerto Inca', count: 156 },
    { region: 'Padre Abad', count: 136 },
    { region: 'Bellavista', count: 114 },
    { region: 'Coronel Portillo', count: 75 },
    { region: 'Mariscal Cáceres', count: 70 },
    { region: 'Tambopata', count: 58 },
    { region: 'La Convención', count: 46 },
    { region: 'Satipo', count: 41 },
    { region: 'Alto Amazonas', count: 36 },
    { region: 'Tahuamanu', count: 32 },
    { region: 'San Martín', count: 30 },
    { region: 'Picota', count: 28 },
    { region: 'Ucayali', count: 27 },
    { region: 'Lamas', count: 24 },
    { region: 'Oxapampa', count: 21 },
    { region: 'Huallaga', count: 17 },
    { region: 'Chanchamayo', count: 12 },
    { region: 'Marañón', count: 12 },
    { region: 'Tocache', count: 9 },
    { region: 'El Dorado', count: 9 },
  ],
  '2010': [
    { region: 'Puerto Inca', count: 227 },
    { region: 'Padre Abad', count: 174 },
    { region: 'Mariscal Cáceres', count: 140 },
    { region: 'Bellavista', count: 135 },
    { region: 'Coronel Portillo', count: 133 },
    { region: 'Oxapampa', count: 106 },
    { region: 'Tambopata', count: 82 },
    { region: 'Alto Amazonas', count: 80 },
    { region: 'Tahuamanu', count: 69 },
    { region: 'La Convención', count: 57 },
    { region: 'Lamas', count: 52 },
    { region: 'Leoncio Prado', count: 51 },
    { region: 'Picota', count: 45 },
    { region: 'Satipo', count: 40 },
    { region: 'Ucayali', count: 38 },
    { region: 'Tocache', count: 30 },
    { region: 'San Martín', count: 30 },
    { region: 'Marañón', count: 27 },
    { region: 'Mariscal Ramón Castilla', count: 21 },
    { region: 'Huallaga', count: 19 },
  ],
  '2011': [
    { region: 'Puerto Inca', count: 151 },
    { region: 'Bellavista', count: 126 },
    { region: 'Padre Abad', count: 108 },
    { region: 'Mariscal Cáceres', count: 91 },
    { region: 'Coronel Portillo', count: 70 },
    { region: 'Oxapampa', count: 62 },
    { region: 'Tahuamanu', count: 47 },
    { region: 'Alto Amazonas', count: 44 },
    { region: 'Tambopata', count: 40 },
    { region: 'San Martín', count: 30 },
    { region: 'Leoncio Prado', count: 25 },
    { region: 'Picota', count: 24 },
    { region: 'El Dorado', count: 23 },
    { region: 'Lamas', count: 23 },
    { region: 'Satipo', count: 21 },
    { region: 'Ucayali', count: 21 },
    { region: 'Mariscal Ramón Castilla', count: 19 },
    { region: 'Huallaga', count: 18 },
    { region: 'La Convención', count: 15 },
    { region: 'Tocache', count: 13 },
  ],
  '2012': [
    { region: 'Puerto Inca', count: 317 },
    { region: 'Padre Abad', count: 294 },
    { region: 'Tambopata', count: 128 },
    { region: 'Bellavista', count: 120 },
    { region: 'Coronel Portillo', count: 118 },
    { region: 'Mariscal Cáceres', count: 115 },
    { region: 'Oxapampa', count: 88 },
    { region: 'Leoncio Prado', count: 66 },
    { region: 'Tahuamanu', count: 58 },
    { region: 'Alto Amazonas', count: 56 },
    { region: 'Tocache', count: 55 },
    { region: 'La Convención', count: 51 },
    { region: 'Marañón', count: 49 },
    { region: 'Ucayali', count: 48 },
    { region: 'Huallaga', count: 47 },
    { region: 'Satipo', count: 43 },
    { region: 'Lamas', count: 43 },
    { region: 'Picota', count: 33 },
    { region: 'La Mar', count: 24 },
    { region: 'San Martín', count: 24 },
  ],
  '2013': [
    { region: 'Puerto Inca', count: 211 },
    { region: 'Padre Abad', count: 151 },
    { region: 'Coronel Portillo', count: 110 },
    { region: 'Bellavista', count: 96 },
    { region: 'Mariscal Cáceres', count: 79 },
    { region: 'Tambopata', count: 74 },
    { region: 'Tahuamanu', count: 68 },
    { region: 'Ucayali', count: 37 },
    { region: 'Oxapampa', count: 34 },
    { region: 'Alto Amazonas', count: 30 },
    { region: 'San Martín', count: 26 },
    { region: 'Huallaga', count: 25 },
    { region: 'Picota', count: 23 },
    { region: 'Lamas', count: 20 },
    { region: 'El Dorado', count: 19 },
    { region: 'Satipo', count: 18 },
    { region: 'Chanchamayo', count: 16 },
    { region: 'Leoncio Prado', count: 15 },
    { region: 'Tocache', count: 15 },
    { region: 'La Convención', count: 13 },
  ],
  '2014': [
    { region: 'Padre Abad', count: 132 },
    { region: 'Puerto Inca', count: 131 },
    { region: 'Tambopata', count: 77 },
    { region: 'Tahuamanu', count: 63 },
    { region: 'Coronel Portillo', count: 52 },
    { region: 'Mariscal Cáceres', count: 50 },
    { region: 'Oxapampa', count: 44 },
    { region: 'Bellavista', count: 29 },
    { region: 'Leoncio Prado', count: 23 },
    { region: 'Huallaga', count: 21 },
    { region: 'Ucayali', count: 20 },
    { region: 'Satipo', count: 18 },
    { region: 'Marañón', count: 18 },
    { region: 'Alto Amazonas', count: 18 },
    { region: 'San Martín', count: 16 },
    { region: 'Tocache', count: 14 },
    { region: 'Picota', count: 12 },
    { region: 'Lamas', count: 12 },
    { region: 'La Convención', count: 11 },
    { region: 'Manu', count: 11 },
  ],
  '2015': [
    { region: 'Padre Abad', count: 304 },
    { region: 'Puerto Inca', count: 276 },
    { region: 'Coronel Portillo', count: 127 },
    { region: 'Tambopata', count: 80 },
    { region: 'Tahuamanu', count: 77 },
    { region: 'Mariscal Cáceres', count: 76 },
    { region: 'Bellavista', count: 66 },
    { region: 'Oxapampa', count: 55 },
    { region: 'Satipo', count: 53 },
    { region: 'Ucayali', count: 43 },
    { region: 'San Martín', count: 27 },
    { region: 'La Convención', count: 26 },
    { region: 'Atalaya', count: 22 },
    { region: 'Leoncio Prado', count: 19 },
    { region: 'Lamas', count: 19 },
    { region: 'Tocache', count: 18 },
    { region: 'Alto Amazonas', count: 18 },
    { region: 'Huallaga', count: 17 },
    { region: 'Marañón', count: 15 },
    { region: 'Chanchamayo', count: 12 },
  ],
  '2016': [
    { region: 'Padre Abad', count: 136 },
    { region: 'Coronel Portillo', count: 126 },
    { region: 'Puerto Inca', count: 125 },
    { region: 'Tambopata', count: 116 },
    { region: 'Tahuamanu', count: 108 },
    { region: 'Bellavista', count: 101 },
    { region: 'Mariscal Cáceres', count: 75 },
    { region: 'Satipo', count: 58 },
    { region: 'Oxapampa', count: 52 },
    { region: 'Alto Amazonas', count: 41 },
    { region: 'La Convención', count: 34 },
    { region: 'Lamas', count: 34 },
    { region: 'Huallaga', count: 32 },
    { region: 'Leoncio Prado', count: 29 },
    { region: 'Tocache', count: 28 },
    { region: 'San Martín', count: 28 },
    { region: 'Chota', count: 26 },
    { region: 'Atalaya', count: 25 },
    { region: 'Ucayali', count: 21 },
    { region: 'Picota', count: 21 },
  ],
  '2017': [
    { region: 'Coronel Portillo', count: 139 },
    { region: 'Puerto Inca', count: 136 },
    { region: 'Padre Abad', count: 119 },
    { region: 'Tambopata', count: 93 },
    { region: 'Tahuamanu', count: 77 },
    { region: 'Oxapampa', count: 55 },
    { region: 'Satipo', count: 27 },
    { region: 'Mariscal Cáceres', count: 27 },
    { region: 'Alto Amazonas', count: 25 },
    { region: 'Ucayali', count: 24 },
    { region: 'Bellavista', count: 23 },
    { region: 'La Convención', count: 20 },
    { region: 'San Martín', count: 17 },
    { region: 'Atalaya', count: 15 },
    { region: 'Lamas', count: 15 },
    { region: 'Leoncio Prado', count: 11 },
    { region: 'Tocache', count: 9 },
    { region: 'Chanchamayo', count: 8 },
    { region: 'Manu', count: 7 },
    { region: 'Huanta', count: 7 },
  ],
  '2018': [
    { region: 'Puerto Inca', count: 246 },
    { region: 'Padre Abad', count: 147 },
    { region: 'Coronel Portillo', count: 135 },
    { region: 'Tahuamanu', count: 91 },
    { region: 'Tambopata', count: 81 },
    { region: 'Bellavista', count: 72 },
    { region: 'Oxapampa', count: 61 },
    { region: 'Satipo', count: 40 },
    { region: 'Mariscal Cáceres', count: 36 },
    { region: 'San Martín', count: 35 },
    { region: 'Ucayali', count: 32 },
    { region: 'Lamas', count: 29 },
    { region: 'Atalaya', count: 27 },
    { region: 'Marañón', count: 22 },
    { region: 'Tocache', count: 22 },
    { region: 'Picota', count: 21 },
    { region: 'Alto Amazonas', count: 21 },
    { region: 'La Convención', count: 20 },
    { region: 'Leoncio Prado', count: 20 },
    { region: 'Huallaga', count: 17 },
  ],
  '2019': [
    { region: 'Coronel Portillo', count: 303 },
    { region: 'Puerto Inca', count: 252 },
    { region: 'Padre Abad', count: 207 },
    { region: 'Tambopata', count: 136 },
    { region: 'Tahuamanu', count: 108 },
    { region: 'Satipo', count: 75 },
    { region: 'Oxapampa', count: 61 },
    { region: 'Ucayali', count: 55 },
    { region: 'Bellavista', count: 53 },
    { region: 'Atalaya', count: 41 },
    { region: 'Marañón', count: 38 },
    { region: 'Alto Amazonas', count: 37 },
    { region: 'San Martín', count: 36 },
    { region: 'La Convención', count: 32 },
    { region: 'Manu', count: 32 },
    { region: 'Mariscal Cáceres', count: 31 },
    { region: 'Tocache', count: 30 },
    { region: 'Leoncio Prado', count: 28 },
    { region: 'Chanchamayo', count: 21 },
    { region: 'Lamas', count: 18 },
  ],
  '2020': [
    { region: 'Coronel Portillo', count: 222 },
    { region: 'Tambopata', count: 177 },
    { region: 'Padre Abad', count: 147 },
    { region: 'Puerto Inca', count: 129 },
    { region: 'Satipo', count: 99 },
    { region: 'Tahuamanu', count: 82 },
    { region: 'Bellavista', count: 80 },
    { region: 'Oxapampa', count: 76 },
    { region: 'Atalaya', count: 60 },
    { region: 'La Convención', count: 42 },
    { region: 'Alto Amazonas', count: 40 },
    { region: 'Manu', count: 37 },
    { region: 'Mariscal Cáceres', count: 34 },
    { region: 'Chanchamayo', count: 32 },
    { region: 'Ucayali', count: 26 },
    { region: 'San Martín', count: 26 },
    { region: 'Marañón', count: 19 },
    { region: 'Huallaga', count: 16 },
    { region: 'Sandia', count: 15 },
    { region: 'Lamas', count: 15 },
  ],
  '2021': [
    { region: 'Puerto Inca', count: 177 },
    { region: 'Coronel Portillo', count: 163 },
    { region: 'Padre Abad', count: 152 },
    { region: 'Tambopata', count: 150 },
    { region: 'Tahuamanu', count: 126 },
    { region: 'Satipo', count: 82 },
    { region: 'Bellavista', count: 68 },
    { region: 'Atalaya', count: 36 },
    { region: 'Manu', count: 29 },
    { region: 'Picota', count: 29 },
    { region: 'Mariscal Cáceres', count: 28 },
    { region: 'San Martín', count: 28 },
    { region: 'Alto Amazonas', count: 27 },
    { region: 'Ucayali', count: 26 },
    { region: 'Oxapampa', count: 25 },
    { region: 'Chanchamayo', count: 22 },
    { region: 'Mariscal Ramón Castilla', count: 21 },
    { region: 'La Convención', count: 17 },
    { region: 'Tocache', count: 16 },
    { region: 'Lamas', count: 14 },
  ],
  '2022': [
    { region: 'Coronel Portillo', count: 266 },
    { region: 'Puerto Inca', count: 228 },
    { region: 'Padre Abad', count: 215 },
    { region: 'Tahuamanu', count: 170 },
    { region: 'Tambopata', count: 102 },
    { region: 'Bellavista', count: 96 },
    { region: 'Ucayali', count: 60 },
    { region: 'Oxapampa', count: 52 },
    { region: 'Mariscal Cáceres', count: 50 },
    { region: 'Atalaya', count: 43 },
    { region: 'La Convención', count: 41 },
    { region: 'Alto Amazonas', count: 40 },
    { region: 'Satipo', count: 35 },
    { region: 'Picota', count: 32 },
    { region: 'Huallaga', count: 30 },
    { region: 'Lamas', count: 24 },
    { region: 'Chanchamayo', count: 19 },
    { region: 'San Martín', count: 19 },
    { region: 'Manu', count: 16 },
    { region: 'Tocache', count: 15 },
  ],
  '2023': [
    { region: 'Coronel Portillo', count: 219 },
    { region: 'Puerto Inca', count: 216 },
    { region: 'Padre Abad', count: 191 },
    { region: 'Tambopata', count: 125 },
    { region: 'Tahuamanu', count: 113 },
    { region: 'Bellavista', count: 78 },
    { region: 'Ucayali', count: 66 },
    { region: 'Oxapampa', count: 51 },
    { region: 'Atalaya', count: 39 },
    { region: 'San Martín', count: 38 },
    { region: 'Mariscal Cáceres', count: 33 },
    { region: 'Satipo', count: 28 },
    { region: 'Alto Amazonas', count: 28 },
    { region: 'Mariscal Ramón Castilla', count: 27 },
    { region: 'Chanchamayo', count: 23 },
    { region: 'Lamas', count: 20 },
    { region: 'La Convención', count: 19 },
    { region: 'Manu', count: 16 },
    { region: 'Huallaga', count: 15 },
    { region: 'Picota', count: 14 },
  ],
  '2024': [
    { region: 'Coronel Portillo', count: 485 },
    { region: 'Tahuamanu', count: 303 },
    { region: 'Padre Abad', count: 273 },
    { region: 'Puerto Inca', count: 188 },
    { region: 'Ucayali', count: 117 },
    { region: 'Tambopata', count: 115 },
    { region: 'Mariscal Cáceres', count: 77 },
    { region: 'Atalaya', count: 75 },
    { region: 'Bellavista', count: 70 },
    { region: 'Satipo', count: 64 },
    { region: 'Huallaga', count: 45 },
    { region: 'Oxapampa', count: 37 },
    { region: 'Leoncio Prado', count: 28 },
    { region: 'Mariscal Ramón Castilla', count: 28 },
    { region: 'Picota', count: 26 },
    { region: 'Lamas', count: 26 },
    { region: 'Manu', count: 24 },
    { region: 'La Convención', count: 23 },
    { region: 'Alto Amazonas', count: 22 },
    { region: 'Marañón', count: 20 },
  ],
}

export const MONTHLY_STATS: { month: string; hotspots: number }[] = [
  { month: 'Jan', hotspots: 636 },
  { month: 'Feb', hotspots: 347 },
  { month: 'Mar', hotspots: 34 },
  { month: 'Apr', hotspots: 68 },
  { month: 'May', hotspots: 83 },
  { month: 'Jun', hotspots: 174 },
  { month: 'Jul', hotspots: 1001 },
  { month: 'Aug', hotspots: 8949 },
  { month: 'Sep', hotspots: 15892 },
  { month: 'Oct', hotspots: 3793 },
  { month: 'Nov', hotspots: 1021 },
  { month: 'Dec', hotspots: 366 },
]
